### ISSUE TITLE
lcgRecursiveCopy only gives status in stdout

### ISSUE THREAD

**Issue by cbeiraod** [vischia/gridTools#2]
The status of the copy is only given to stdout, making the parsing of the status difficult, if not impossible in case you forget to redirect it to a file.
It would be useful to create a log file saying if a copy was successful or not and if possible, print a summary table at the end of the log file... Just a suggestion though.

**Comment by vischia** [comment]
This was already fixed at some time in the past (a "LOG" file is automatically created).

Closing :)
